-- Initial PostgreSQL schema for ピンゲージ管理DB.
-- Run this before importing Access data.

CREATE TABLE IF NOT EXISTS "pin_gauge_master" (
    "size" varchar(20),
    "owned_quantity" integer,
    "case_no" varchar(5)
);

CREATE TABLE IF NOT EXISTS "staff_master" (
    "staff_id" varchar(2),
    "staff_name" varchar(5),
    "department" varchar(2),
    "kana" varchar(1),
    "display_flag" varchar(1)
);

CREATE TABLE IF NOT EXISTS "pin_gauge_lending" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "size" varchar(20),
    "staff_id" varchar(2),
    "machine_no" varchar(4),
    "lent_date" timestamp,
    "returned_date" timestamp,
    "completion_flag" varchar(1)
);
