-- Initial PostgreSQL schema for ピンゲージ管理.
-- Run this before importing Access data.

CREATE TABLE IF NOT EXISTS "pg_master" (
    "size" varchar(20) NOT NULL,
    "holding_count" integer NOT NULL,
    "case_no" varchar(5)
);

CREATE TABLE IF NOT EXISTS "staff_master" (
    "staff_id" varchar(2) NOT NULL,
    "staff_name" varchar(5) NOT NULL,
    "department" varchar(2) NOT NULL,
    "kana" varchar(1) NOT NULL,
    "visible" varchar(1) NOT NULL
);

CREATE TABLE IF NOT EXISTS "loans" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "size" varchar(20) NOT NULL,
    "staff_id" varchar(2) NOT NULL,
    "machine_code" varchar(4) NOT NULL,
    "lent_on" date NOT NULL,
    "returned_on" date,
    "completion_flag" varchar(1)
);
